name: Datadog
description: |
  Real-time performance tracking and visualization of your container-based application deployment
version: 1.1.0-11.0.5123
category: Monitoring
maintainer: "Jan Bruder <jan@rancher.com>"
license: The MIT License
